name: Typos Check
on: [push, pull_request]
jobs:
  typos:
    name: Spell Check with Typos
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions
      uses: actions/checkout@v4  
      - name: Typos Check
      uses: crate-ci/typos@master
